### ISSUE TITLE
Get CPU overheads estimate

### ISSUE THREAD

**Issue by P403n1x87** [mikeckennedy/pythons-gc-and-orms#1]
This is very instructive, but perhaps could be complemented with CPU overhead estimates to see how they relate to the number of GCs. One way of doing this could be with the GC state sampling option of [Austin](https://github.com/P403n1x87/austin#garbage-collector-sampling).

**Comment by mikeckennedy** [comment]
Thanks @P403n1x87 Austin is neat. I ran it with the GC setting but didn't find the text :GC anywhere. I'm guessing the GC times are very short. Is there a way to ramp up the sampling rate that would help?

**Comment by mikeckennedy** [comment]
Also, I added a bit more details about the problem/situation in the readme for the project.

**Comment by P403n1x87** [comment]
> I ran it with the GC setting but didn't find the text :GC anywhere.

Ah, interesting. The default sampling rate is quite high (1 sample every 100 microseconds). Perhaps those calls to the GC are not so expensive? For comparison, this is the picture produced by the following script

https://github.com/P403n1x87/austin/blob/47dd71c4c45929dfbd29b4479c5cfccf625c2dce/test/target_gc.py#L25-L44

when run with

~~~ console
austin -sgo /tmp/gc.austin python target_gc.py
~~~

The `-s` option is there to get on-CPU samples only.

![gc](https://user-images.githubusercontent.com/20231758/147138640-18fd210d-8f0b-428f-ac89-f45bb35ac4a8.png)

*NOTE* Requires Python >= 3.7 for the `-g` option to actually work.

**Comment by P403n1x87** [comment]
This is what I get when I run (using Python 3.8, and **no** MongoDB server)

~~~ console
austin -sgo test_app.austin python test_app.py
~~~

![test_app](https://user-images.githubusercontent.com/20231758/147139391-95b3041a-676e-4392-b735-b2e762b297ee.png)

**Comment by mikeckennedy** [comment]
Super thanks for running it and generating the picture. I must have been doing it wrong because I only got the terminal trace messages. No Mongo is fine as SQLAlchemy is a worse case between the two.

**Comment by P403n1x87** [comment]
🙌  The picture is a snapshot of the flame graph panel of VS Code that is provided by the Austin extension https://marketplace.visualstudio.com/items?itemName=p403n1x87.austin-vscode

**Comment by mikeckennedy** [comment]
Oh neat. I didn't know it had a VS Code plug in.
